### ISSUE TITLE
Weird selection behaviour

### ISSUE THREAD

**Issue by 2mas** [2mas/SelectNextOccurrence#64]
### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [1.3.150]

### Description
Weird selection behaviour when starting with multiple carets wihout selections

### Steps to recreate
AddCaretBelow three times and then SelectNextOccurrence
![behaviour](https://user-images.githubusercontent.com/372362/82893690-ae14fd80-9f51-11ea-9438-6f5018c9ebc4.gif)

### Current behavior
Misses one occurrence

### Expected behavior
Selects all occurrences

**Comment by Mr-Badger** [comment]
Hmm, weird edge case, seems the selections are overlapping for some reason.
This seems to only occur at the beginning of a line, the line contains a single word, it can contain spaces after the word but not before, this also happens when spaces are the only thing on the line.
This also only seems to happen when carets are in ascending order and not when they're in descending order.
Maybe this has to do with the end of word selection I implemented.

**Comment by Mr-Badger** [comment]
Added a PR that should fix this
